### ISSUE TITLE
px.js assumes Angular ng-app is on the body tag

### ISSUE THREAD

**Issue by bsyk** [PredixDev/px-card#10]
The issue we are seeing is that the implementation of `window.px.dealer.getHttpProvider` in px.min.js assumes that the Angular app is defined on the body tag.  But when building a micro-app, the angular app is typically attached to a div within the pxh-wrapper as the body tag can be provided by another template and not the micro-app.

Here’s the definition from px.min.js:

```
function(){
  var a=null;
  return this.httpProvider ? this.httpProvider : 
    (window.angular && (a = angular.element("body").injector().get("$http")), a)
}
```

Here’s what we’ve tried as a work-around:

```
window.px.dealer.getHttpProvider = function(){
  var a=null;
  return this.httpProvider ? this.httpProvider : 
    (window.angular && (a = angular.element(".ng-scope").injector().get("$http")), a)
}
```

**Comment by runn-vermel** [comment]
Hi Ben,

Can you please submit this as a Pull request? I'll be happy to change it over - this makes perfect sense.

**Comment by randyaskin** [comment]
I think px.js was moved to its own repo or possibly the webapp-starter. Also based on Runn's comment in the PR I'm not sure if this is still valid?
