### ISSUE TITLE
Build is failed and chevron not working

### ISSUE THREAD

**Issue by jennifergouin** [PredixDev/px-card#11]
Hello

Build of px-card component is currently failed (v0.6.4)
Do you plan to fix it ?
If yes, when do you think we can have it working again ?
By the way, chevron is not working, is it linked ?

Thanks
Regards
Jennifer

**Comment by randyaskin** [comment]
There was a small typo in the demo page for px-card that was preventing the chevron from working. Fixed now! Thanks.
