### ISSUE TITLE
Uncaught TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by Abdelkrim** [PredixDev/px-card#12]
# Submit an Issue

The documentation of px-map describes how to download data through an http request. See [sample-card.html#L52](https://github.com/PredixDev/px-card/blob/737b94692f99292299e2d2e47eb3c36e3f81c0a1/px-sample-card.html#L52)

unfortunately, the code does not work on my machine due to the following error : 

> optim-view.html:114 Uncaught TypeError: Cannot read property 'then' of undefined
>     at HTMLElement.ready (optim-view.html:114)
>     at HTMLElement._readySelf (polymer-mini.html:91)
>     at HTMLElement._ready (polymer-mini.html:71)
>     at HTMLElement._tryReady (polymer-mini.html:56)
>     at HTMLElement._initFeatures (polymer.html:4168)
>     at HTMLElement.__initialize (polymer-micro.html:234)
>     at HTMLElement.createdCallback (polymer-micro.html:217)
>     at HTMLElement._attachElement (px-view.html:219)
>     at HTMLElement._onLoaded (px-view.html:169)
>     at HTMLElement._checkStatus (px-view.html:214)

Here is the code 
```
<dom-module id="optim-view">
  <template>
    <h1> hello world, temp is "{{currentTemperature}}"</h1>
<script>
  Polymer({
    is: 'optim-view',
    properties: {},

    ready: function () {
      
      //Example:
      this.getData('/file.json').then(function (data) {
        // on fulfillment
        self.currentTemperature = data.value;
      }, function (reason) {
        // on rejection
        console.error('ERROR', reason);
      });

    },
    behaviors: [px.card],
    getData: function (url, httpConfig) {
      //getData from web resources with url, config is optional
    }

  });
```

## Expected behavior and actual behavior:

The http request is performed and the data are collected

## Steps to reproduce the problem:

Copy-paste the piece of code described here above into a polymer file and run the code

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

* windows 7
* node v6.10.3

## Screenshots (_optional, but very helpful_):

* NOT RELEVANT

## Code examples help us better understand the issue 

* NOT RELEVANT

**Comment by nonmetalhail** [comment]
You appear to be overwriting the getData method from the behavior with your local method.
