### ISSUE TITLE
Custom style variables?

### ISSUE THREAD

**Issue by ahrobinson** [PredixDev/px-card#14]
Hi,

I am unsure if this is a Polymer, css or px-card issue.
When trying to change the color of the icon using --px-card-icon-color, it is not actually changing the color.

I have tried using :host, :root, ::content, custom id on px-card to no avail.

Thanks.

**Comment by randyaskin** [comment]
--px-card-icon-color is only available as a CSS variable in the v1 prerelease of the component, which you should not be using yet. Are you attempting to use the new variable on an older version of the component? 

That being said, I've tested the CSS variable in my local environment and it works as expected with the new prerelease component. If you're using the var at the application level, you have to remember to wrap it in a `<style is="custom-style">` block [per the Polymer documentation](https://www.polymer-project.org/1.0/docs/devguide/styling#custom-style).

**Comment by ahrobinson** [comment]
Ahh I see. We are using an earlier version, but I saw that as I was reading through the code..my mistake! Thanks!
