### ISSUE TITLE
Empty header-text leaves unsightly empty space

### ISSUE THREAD

**Issue by austinmcdaniel** [PredixDev/px-card#17]
## Expected behavior and actual behavior:
In the latest release if the header-text is left empty the header space is still consumed with a large empty block.

## Steps to reproduce the problem:
Use px-card without setting the header text.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
px-card v1.0.8
Chrome 60.0.3112.113
Windows

**Comment by randyaskin** [comment]
Added dom-if and notes to the documentation in v1.0.9.
