### ISSUE TITLE
Named-slot content not rendering in expected place

### ISSUE THREAD

**Issue by squidbe** [PredixDev/px-card#18]
## Expected behavior and actual behavior:
Using `slot="actions"` on a child element of **px-card** should render that content in the named slot, but it's rendered in the same place it appears in my template's DOM.
All other content is loading normally, and no errors appear in the browser console.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
polymer2.0-preview
Chrome 61
Mac El Capitan

## Screenshots (_optional, but very helpful_):
The "pause" button should appear in upper right:

![screen shot 2017-09-19 at 10 26 31 am](https://user-images.githubusercontent.com/1664227/30606011-0d5a7680-9d25-11e7-94fd-595993282f22.png)

## Code example
Here's my code:

      <px-card header-text="Header Text">
        <div class="app-stats layout layout__item u-1/2">
          <div slot="actions" class='actions'>
            <px-icon icon="px-nav:pause"></px-icon>
          </div>
        </div>
      </px-card>

Here is rendered DOM (copied from browser console):

![screen shot 2017-09-19 at 11 06 02 am](https://user-images.githubusercontent.com/1664227/30607648-94553918-9d2a-11e7-872d-b82da6f0666c.png)

**Comment by randyaskin** [comment]
Per the Polymer [documentation](https://www.polymer-project.org/2.0/docs/devguide/shadow-dom#shadow-dom-and-composition), `a named slot only accepts top-level children that have a matching slot attribute`, so it needs to go outside of your layout div, e.g.

```
<px-card header-text="Header Text">
  <div slot="actions" class='actions'>
    <px-icon icon="px-nav:pause"></px-icon>
  </div>
  <div class="app-stats layout layout__item u-1/2">
    <!-- Other content here -->
  </div>
</px-card>
```
