### ISSUE TITLE
Cards display browser tooltip on hover with card name

### ISSUE THREAD

**Issue by lrbridge** [PredixDev/px-card#3]
When you hover over a card you see a browser tooltip with the name of the card.

<img width="1186" alt="screen shot 2015-12-09 at 3 32 06 pm" src="https://cloud.githubusercontent.com/assets/6046316/11702248/15b29eac-9e8a-11e5-9f9f-9b92c63c3b8b.png">

Looks like this is due to "title" being used as a property of px-card... we should maybe rename it to a non-browser-reserved word.

```
addCard: function (cardName, cardId, title, attributes) {
            if (!cardName || !cardId) {
                throw 'Add card must be called with a card name and card id';
            }
            var newCard = document.createElement(cardName);
            newCard.setAttribute('id', 'card-'+cardId);
            newCard.setAttribute('title', title);
            newCard.setAttribute('context', '{{context}}');
```

**Comment by nonmetalhail** [comment]
@carlosfhernandez Can you please create a rally story for this?

**Comment by ek** [comment]
@lrbridge Great suggestion, we will get this into the next version of px-card

**Comment by randyaskin** [comment]
The API for px-card indicates that the property was changed from `title` to `header-text` at some point.
