### ISSUE TITLE
header-text should not be hard-coded all CAPS

### ISSUE THREAD

**Issue by kornfein** [PredixDev/px-card#8]
The header-text ignores the case of the text you put in making everything all CAPS. For example:
        <px-card id="tableCard" header-text="Hours Details for Work Order M1234">
becomes 
HOURS DETAIL FOR WORK ORDER M1234

very confusing

**Comment by randyaskin** [comment]
That is the design standard set forth by both [Predix UI](http://www.gesdh.com/predix/platform/components/cards/) and [APM](http://www.gesdh.com/predix/product/components/cards-for-apm/) for the header of cards.

**Comment by kornfein** [comment]
Seems like something that should be reviewed / changed. The header text may contain text where the case may be important to the meaning of the text for example part numbers and abbreviations.  In our case reviewers just thought the all CAPS looked bad.

**Comment by mdwragg** [comment]
Hi, I will send this feedback to our designers. I'll close this as it is not a defect per se in the implementation of this component. Thanks for your feedback, we appreciate it.
