### ISSUE TITLE
Override the CSS of the px-card header so that the solid line doesn't display

### ISSUE THREAD

**Issue by adrian-gonzalez** [PredixDev/px-card#9]
Hi, is there a way that I can pass an attribute to the px-card in order to override the default solid line below the header? The image below is the default card behavior.
![image](https://cloud.githubusercontent.com/assets/9535962/19126517/221daeea-8af0-11e6-97b3-3b066761b9a5.png)

What I'm trying to accomplish is something like the image below:
![image](https://cloud.githubusercontent.com/assets/9535962/19126583/5e28db30-8af0-11e6-8203-433891fbf225.png)

**Comment by randyaskin** [comment]
FYI this is now achievable. As part of theming, we've exposed a style variable for the border-color, so you could set it to white or transparent or something. Example Codepen [here](http://codepen.io/randyaskin/pen/LxEaLN?editors=1000).
